/*
 * Fonte única dos modelos de aeronaves usados em Modelos e no Simulador de Voo.
 * velocidadeKmh é a velocidade de cruzeiro em km/h usada no cálculo de tempo de voo
 * (derivada de "velocidade" quando esta é um número Mach: km/h = Mach * 1063).
 * sketchfabId (opcional): UID do modelo 3D no Sketchfab, exibido ao passar o mouse sobre
 * o card em Modelos. Use apenas modelos com licença CC Attribution (ou similar) verificada
 * manualmente — sketchfabAuthor vira o crédito exigido pela licença.
 */
window.AIRCRAFT_MODELS = [
	{ manufacturer: 'Airbus', name: 'Airbus A220-300', image: 'https://f.i.uol.com.br/fotografia/2026/06/05/17806916846a2332e467ac6_1780691684_3x2_rt.jpg', alt: 'Airbus A220-300', tipo: 'Regional', passageiros: '160', autonomia: '6.300 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2016.', 'É um dos jatos regionais de maior eficiência e apelo operacional.', 'Sua cabine moderna e alcance fazem dele um campeão de rotas de média distância.'], sketchfabId: '210239f0f9bd4e91bbca93e3e1c227ee', sketchfabAuthor: 'kristapssteimanis' },
	{ manufacturer: 'Airbus', name: 'Airbus A319neo', image: 'https://aviationnews-online.com/public/storage/news/airbus-a319.jpg', alt: 'Airbus A319neo', tipo: 'Single-aisle', passageiros: '156', autonomia: '6.900 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2018.', 'É uma versão enxuta da família A320 com foco em eficiência e densidade.', 'Sua versatilidade é muito útil em rotas domésticas e de curta distância.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A320neo', image: 'https://www.aircraft.airbus.com/sites/g/files/jlcbta126/files/styles/w1200h675/public/2025-10/Aircraft.Airbus%20Figma%20Images%20V2_A320neo.png?h=eb58b4d6&itok=m1AYlns4', alt: 'Airbus A320neo', tipo: 'Single-aisle', passageiros: '180', autonomia: '6.100 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2016.', 'É uma das famílias mais utilizadas em rotas médias e de alta demanda.', 'Seu projeto prioriza eficiência, capacidade e operação econômica.'], sketchfabId: '665566f4a21a422fbf34eae4c4010eb2', sketchfabAuthor: 'coderxx' },
	{ manufacturer: 'Airbus', name: 'Airbus A321neo', image: 'https://voerima.com.br/wp-content/uploads/2024/01/a321_plane.jpg', alt: 'Airbus A321neo', tipo: 'Single-aisle', passageiros: '220', autonomia: '7.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2016.', 'Oferece maior alcance e capacidade em comparação ao A320neo.', 'Seu uso é comum em rotas de alta demanda e média distância.'], sketchfabId: '542713418c7f47ce9c71d3d0b23921e3', sketchfabAuthor: '1883' },
	{ manufacturer: 'Airbus', name: 'Airbus A330-200', image: 'https://dlwwkvaei5hfp.cloudfront.net/aircrafts/models/164/1659961426262406.jpg', alt: 'Airbus A330-200', tipo: 'Longo curso', passageiros: '250', autonomia: '13.450 km', velocidade: 'Mach 0.86', velocidadeKmh: 915, descricao: ['Produção iniciada em 1998.', 'Foi uma solução muito eficiente para rotas intercontinentais e fora de hubs.', 'Sua capacidade e alcance impulsionaram o mercado de longo curso.'], sketchfabId: '95f54686b7d845ca878c764b9c734488', sketchfabAuthor: 'A350-900HQS' },
	{ manufacturer: 'Airbus', name: 'Airbus A330neo', image: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Airbus_A330neo_first_take-off_%28cropped%29.jpg?utm_source=pt.wikipedia.org&utm_campaign=index&utm_content=original', alt: 'Airbus A330neo', tipo: 'Longo curso', passageiros: '300', autonomia: '12.500 km', velocidade: 'Mach 0.86', velocidadeKmh: 915, descricao: ['Produção iniciada em 2018.', 'Sua cabine ampla e maior eficiência ajudam em rotas intercontinentais.', 'É uma opção muito valorizada por companhias de longo curso.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A350-900', image: 'https://www.aircraft.airbus.com/sites/g/files/jlcbta126/files/styles/w1200h675/public/2024-05/aircraft.airbus_figma_images_v1.1_a350-900.png?h=77b290fb&itok=my4_gJ-X', alt: 'Airbus A350-900', tipo: 'Longo curso', passageiros: '325', autonomia: '16.100 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 2015.', 'É reconhecida por baixo consumo, cabine silenciosa e alcance transcontinental.', 'Sua tecnologia reforça conforto e eficiência em rotas de longa duração.'], sketchfabId: '09f4a206ec89489b82609b6df630dc85', sketchfabAuthor: 'arya.g.winarto' },

	{ manufacturer: 'Boeing', name: 'Boeing 737-800', image: 'https://www.seudinheiro.com/uploads/2022/03/Boeing-737-800.jpg', alt: 'Boeing 737-800', tipo: 'Single-aisle', passageiros: '162', autonomia: '5.700 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 1998.', 'É um dos modelos mais importantes do segmento de jatos de curto e médio alcance.', 'Sua operação é altamente eficiente em redes domésticas e regionais.'], sketchfabId: '7a548b5ba64340f78f7c58d23781ffe9', sketchfabAuthor: 'andriiharbut' },
	{ manufacturer: 'Boeing', name: 'Boeing 737 MAX 8', image: 'https://www.melhoresdestinos.com.br/wp-content/uploads/2026/05/boeing-737-max-8.jpeg', alt: 'Boeing 737 MAX 8', tipo: 'Single-aisle', passageiros: '178', autonomia: '6.570 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 2017.', 'É um modelo muito usado em rotas domésticas e regionais de alta frequência.', 'Sua proposta combina capacidade, eficiência e operação em alta demanda.'], sketchfabId: '197ae72ceb5441efa91b8bdc2ee37050', sketchfabAuthor: 'AMGP3D' },
	{ manufacturer: 'Boeing', name: 'Boeing 737 MAX 10', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHOKiYU0dNvfo63sY3YIC9Sf0wGkpEmqlhoIeAvZK1AXfwj_rQVQSXAsk&s=10', alt: 'Boeing 737 MAX 10', tipo: 'Single-aisle', passageiros: '188', autonomia: '6.790 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 2020.', 'Amplia a capacidade da família MAX para redes de grande demanda.', 'A proposta prioriza eficiência e melhora operacional em aeroportos congestionados.'], sketchfabId: '2e3bdccfa5b9489b98be1fcaa6628930', sketchfabAuthor: 'AirplaneChef' },
	{ manufacturer: 'Boeing', name: 'Boeing 747-400', image: 'https://t.ctcdn.com.br/jSmxDsrSyvzeVBUMUa7t55MuV80=/1024x576/smart/i689336.jpeg', alt: 'Boeing 747-400', tipo: 'Longo curso', passageiros: '410', autonomia: '13.450 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 1988.', 'Foi um marco da aviação comercial por sua capacidade e alcance.', 'Sua fuselagem ampla o manteve relevante em rotas de grande demanda.'], sketchfabId: 'fe4404f035304e6db0985da352c175cb', sketchfabAuthor: 'Afirus' },
	{ manufacturer: 'Boeing', name: 'Boeing 767-300ER', image: 'https://flyflapper.com/_next/image?url=https%3A%2F%2Fdlwwkvaei5hfp.cloudfront.net%2Faircrafts%2F1927%2F1687952015493261.jpg.webp&w=828&q=75', alt: 'Boeing 767-300ER', tipo: 'Longo curso', passageiros: '261', autonomia: '11.450 km', velocidade: 'Mach 0.80', velocidadeKmh: 850, descricao: ['Produção iniciada em 1986.', 'Foi uma solução eficiente para rotas intercontinentais e de alta regularidade.', 'Sua utilização se destacou em operação de longo alcance e alto padrão.'], sketchfabId: 'cc2c62f56cd94a7c8b2c586515b378e7', sketchfabAuthor: 'manilov.ap' },
	{ manufacturer: 'Boeing', name: 'Boeing 777-300ER', image: 'https://www.super-hobby.pt/zdjecia/7/0/5/15098_rd.jpg', alt: 'Boeing 777-300ER', tipo: 'Longo curso', passageiros: '396', autonomia: '13.650 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 2004.', 'Destaca-se por grande capacidade e alcance em voos internacionais.', 'É uma das aeronaves mais importantes em rotas de alta densidade.'], sketchfabId: '053d8133bab3489199a946bccea3fdf1', sketchfabAuthor: 'savounited' },
	{ manufacturer: 'Boeing', name: 'Boeing 787-9 Dreamliner', image: 'https://i.ytimg.com/vi/3DY0u3n2Dnk/maxresdefault.jpg', alt: 'Boeing 787-9 Dreamliner', tipo: 'Longo curso', passageiros: '318', autonomia: '14.140 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 2011.', 'Sua estrutura leve em compósito reduz peso e melhora a eficiência do combustível.', 'É reconhecido pelo conforto da cabine e o desempenho de longo alcance.'], sketchfabId: 'b6711e2e698e4e469675c1154a50b7a3', sketchfabAuthor: 'nobilishornet2' },

	{ manufacturer: 'Embraer', name: 'Embraer ERJ 145', image: 'https://www.infomoney.com.br/wp-content/uploads/2025/08/embraer-commericalaviation-ejj145xr.jpg?fit=1280%2C720&quality=50&strip=all', alt: 'Embraer ERJ 145', tipo: 'Regional', passageiros: '50', autonomia: '3.000 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1996.', 'Foi um avião regional muito usado em conexões domésticas e curtas distâncias.', 'Seu desenho compacto e robustez o tornaram um clássico regional.'], sketchfabId: 'd0e93f7b8717493b959d797cad7a7051', sketchfabAuthor: 'helijah' },
	{ manufacturer: 'Embraer', name: 'Embraer E170', image: 'https://static0.simpleflyingimages.com/wordpress/wp-content/uploads/2023/02/ac-170-001418-a.jpg', alt: 'Embraer E170', tipo: 'Regional', passageiros: '80', autonomia: '3.900 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2007.', 'É um dos modelos mais versáteis do segmento regional de baixa e média rotas.', 'Seu desempenho combina conforto e eficiência em operação frequente.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E175', image: 'https://s2-g1.glbimg.com/xoQif_9wbUwpW5FX6AygodyXgEQ=/0x0:569x369/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2017/4/Z/aynbZQTdSpMA1KFbo1dQ/e175.jpg', alt: 'Embraer E175', tipo: 'Regional', passageiros: '76', autonomia: '3.300 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2004.', 'É muito usada em redes regionais por sua versatilidade e operação econômica.', 'Seu tamanho e eficiência o tornam ideal para voos de curta e média distância.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E190-E2', image: 'https://www.embraer.com/media/1bkhjr2u/commercial-e190-2.jpg?v=1dd145c3e09f690', alt: 'Embraer E190-E2', tipo: 'Regional', passageiros: '114', autonomia: '5.500 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2018.', 'Tem cabine mais silenciosa e boa eficiência operacional em rotas médias.', 'É uma escolha frequente para mercados com alta necessidade regional.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E195-E2', image: 'https://www.cavok.com.br/wp-content/uploads/2016/11/E195-E2-Embraer.jpg', alt: 'Embraer E195-E2', tipo: 'Regional', passageiros: '136', autonomia: '5.000 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2019.', 'É destaque em rotas densas e de alta demanda com maior conforto a bordo.', 'Sua capacidade e economia operacional reforçam a eficiência regional.'] },

	{ manufacturer: 'McDonnell Douglas', name: 'DC-9', image: 'https://i.redd.it/i4dqtarcp3aa1.jpg', alt: 'Douglas DC-9', tipo: 'Single-aisle', passageiros: '130', autonomia: '3.500 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1965.', 'Foi um marco da aviação regional de alta frequência e operação econômica.', 'Sua presença no mercado foi fundamental para o crescimento das rotas domésticas.'], sketchfabId: '6eda1534ecc44f30b936b14c3a899716', sketchfabAuthor: '1883' },
	{ manufacturer: 'McDonnell Douglas', name: 'MD-80', image: 'https://media.gettyimages.com/id/813598/pt/foto/the-md-80-shown-in-flight-an-american-airlines-md-80-jet-crashed-june-2-in-little-rock-ark-flight.jpg?s=612x612&w=gi&k=20&c=sx5w5-Rsg-hCxGCHntmw7Pvd69aamq6mEGirX5iPjgk=', alt: 'McDonnell Douglas MD-80', tipo: 'Single-aisle', passageiros: '172', autonomia: '4.000 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1980.', 'A família MD-80 foi muito importante na expansão de rotas médias e curtas.', 'Seu desenho clássico marcou uma era da aviação comercial.'], sketchfabId: 'edf50df831e34af2984132959cdcc7c9', sketchfabAuthor: 'PedriterX' },
	{ manufacturer: 'McDonnell Douglas', name: 'MD-90', image: 'https://mantisserv.com/124/mcdonnell-douglas-md90.jpg', alt: 'McDonnell Douglas MD-90', tipo: 'Single-aisle', passageiros: '172', autonomia: '4.100 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1995.', 'Foi uma evolução da linha MD-80 com foco em eficiência e conforto.', 'Sua busca por melhor performance ajudou a manter a família relevante.'], sketchfabId: 'de86df8080904dafbcae7f4670dff71b', sketchfabAuthor: '1883' },
	{ manufacturer: 'McDonnell Douglas', name: 'MD-11', image: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/TAM_McDonnell_Douglas_MD-11_Bidini.jpg?utm_source=pt.wikipedia.org&utm_campaign=index&utm_content=original', alt: 'McDonnell Douglas MD-11', tipo: 'Longo curso', passageiros: '293', autonomia: '10.600 km', velocidade: 'Mach 0.83', velocidadeKmh: 880, descricao: ['Produção iniciada em 1990.', 'Foi um modelo importante para cargas e voos intercontinentais de longa rota.', 'Seu uso se destacou em operações de alcance e capacidade de carga.'], sketchfabId: '0b3edcf1d1a1476c9bee64a761347565', sketchfabAuthor: 'savounited' },

	{ manufacturer: 'ATR', name: 'ATR 42-600', image: 'https://images.aircharterservice.com/global/aircraft-guide/group-charter/atr-42-1.jpg', alt: 'ATR 42-600', tipo: 'Turboélice', passageiros: '50', autonomia: '1.500 km', velocidade: 'Mach 0.46', velocidadeKmh: 490, descricao: ['Produção iniciada em 2017.', 'É muito eficiente em aeroportos menores e pistas mais curtas.', 'Sua operação é valorizada em redes regionais de baixa densidade.'] },
	{ manufacturer: 'ATR', name: 'ATR 72-500', image: 'https://forbes.com.br/wp-content/uploads/2024/08/atr.png', alt: 'ATR 72-500', tipo: 'Turboélice', passageiros: '68', autonomia: '1.850 km', velocidade: 'Mach 0.48', velocidadeKmh: 510, descricao: ['Produção iniciada em 2007.', 'É uma variante eficiente para rotas regionais e curtas distâncias.', 'Sua operação é reconhecida por confiabilidade e boa performance em aeroportos menores.'] },
	{ manufacturer: 'ATR', name: 'ATR 72-600', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw2S2YLK_bC_0w9Qy-osmjC22JFihYCC9D5-4RPhPOFbZBja05njoXrRSl&s=10', alt: 'ATR 72-600', tipo: 'Turboélice', passageiros: '70', autonomia: '1.900 km', velocidade: 'Mach 0.48', velocidadeKmh: 510, descricao: ['Produção iniciada em 2010.', 'Faz sucesso em rotas regionais por sua confiabilidade e baixo custo operacional.', 'É uma das opções mais reconhecidas para voos de conexão regional.'], sketchfabId: 'c3be63d009f546b697f542cfc4d6f56b', sketchfabAuthor: 'AirplaneChef' },

	{ manufacturer: 'Bombardier', name: 'Bombardier CRJ700', image: 'https://images.aircharterservice.com/global/aircraft-guide/group-charter/bombardier-crj-700-1.jpg', alt: 'Bombardier CRJ700', tipo: 'Regional', passageiros: '78', autonomia: '3.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2001.', 'Faz parte da geração de jatos regionais com alta eficiência operacional.', 'Sua utilização é muito comum em rotas com boa demanda de passageiros.'] },
	{ manufacturer: 'Bombardier', name: 'Bombardier CRJ900', image: 'https://assets.skiesmag.com/wp-content/uploads/2018/01/Bombardier-CRJ900.jpg', alt: 'Bombardier CRJ900', tipo: 'Regional', passageiros: '90', autonomia: '3.700 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2007.', 'É uma evolução do CRJ700 para rotas com maior densidade de passageiros.', 'Sua eficiência e boa execução operacional reforçaram seu uso regional.'], sketchfabId: '02c4fa44604243c2bb48db64506a39af', sketchfabAuthor: 'artoud' },
	{ manufacturer: 'Bombardier', name: 'Bombardier Q400', image: 'https://cdn.aerocontact.com/public/img/aviaexpo/produits/images/573/detail_q400_900x636.jpg', alt: 'Bombardier Q400', tipo: 'Turboélice', passageiros: '86', autonomia: '2.200 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 2008.', 'É muito respeitada por operar em aeroportos curtos e de baixa demanda.', 'Se destaca por conforto, eficiência e boa performance regional.'], sketchfabId: '5b13a73be7d74161a3a9f9ce982a8345', sketchfabAuthor: 'sofyankurniawan' },
	{ manufacturer: 'Bombardier', name: 'Bombardier Q300', image: 'https://www.airport-technology.com/wp-content/uploads/sites/14/2024/11/Q300_1.jpg', alt: 'Bombardier Q300', tipo: 'Turboélice', passageiros: '56', autonomia: '1.750 km', velocidade: 'Mach 0.56', velocidadeKmh: 595, descricao: ['Produção iniciada em 1998.', 'É uma opção confiável para rotas de baixa densidade e pistas curtas.', 'Sua operação combina eficiência regional e conforto de cabine.'] },

	{ manufacturer: 'Cessna', name: 'Cessna 172 Skyhawk', image: 'https://aeroin.net/wp-content/uploads/2025/07/Cessna-172-Skyhawk-25071801.jpg', alt: 'Cessna 172 Skyhawk', tipo: 'Monomotor', passageiros: '4', autonomia: '1.300 km', velocidade: '220 km/h', velocidadeKmh: 220, descricao: ['Produção iniciada em 1956.', 'É a aeronave mais produzida da história e símbolo do treinamento de pilotos.', 'Sua simplicidade e confiabilidade a tornaram universalmente conhecida.'], sketchfabId: 'd1b15841c29c43d0862667300bad55a4', sketchfabAuthor: 'ioai25312' },
	{ manufacturer: 'Cessna', name: 'Cessna 208 Caravan', image: 'https://images.aircharterservice.com/global/aircraft-guide/private-charter/cessna-208-grand-caravan-.jpg', alt: 'Cessna 208 Caravan', tipo: 'Turboélice', passageiros: '9', autonomia: '1.500 km', velocidade: '300 km/h', velocidadeKmh: 300, descricao: ['Produção iniciada em 1984.', 'É muito usada em operações regionais, carga leve e acesso a aeroportos menores.', 'Sua versatilidade faz dela um dos modelos mais úteis do segmento.'] },
	{ manufacturer: 'Cessna', name: 'Cessna Citation Bravo', image: 'https://aeroaffaires.fr/wp-content/uploads/2019/04/y2njy2vjmmutmjfhmi00njlilwe5nmmtmwrmnjhhndnjy2jj_cessna-c550-citation-bravo-privatefly-aa9987.jpg', alt: 'Cessna Citation Bravo', tipo: 'Jato executivo', passageiros: '8', autonomia: '3.000 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 2005.', 'É uma plataforma executiva reconhecida pela combinação de alcance e conforto.', 'Seu uso é muito valorizado em viagens rápidas de negócios e lazer.'] },
	{ manufacturer: 'Cessna', name: 'Cessna Citation CJ4', image: 'https://images.aircharterservice.com/global/aircraft-guide/private-charter/cessna-citation-jet-cj4.jpg', alt: 'Cessna Citation CJ4', tipo: 'Jato executivo', passageiros: '10', autonomia: '3.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2010.', 'Combina alcance, conforto e operação eficiente para voos executivos.', 'É muito valorizada em deslocamentos rápidos com boa produtividade.'] },

	{ manufacturer: 'Fokker', name: 'Fokker 50', image: 'https://flapinternational.com.br/wp-content/uploads/2025/11/IMG_0073.jpg', alt: 'Fokker 50', tipo: 'Turboélice', passageiros: '50', autonomia: '2.200 km', velocidade: 'Mach 0.55', velocidadeKmh: 585, descricao: ['Produção iniciada em 1990.', 'Foi uma referência em operação regional confiável em pistas curtas.', 'Sua confiabilidade ajudou a consolidar a operação em rotas de baixa densidade.'] },
	{ manufacturer: 'Fokker', name: 'Fokker 70', image: 'https://upload.wikimedia.org/wikipedia/commons/6/69/PH-JCT_Fokker_70_KLM_cityhopper.JPG?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original', alt: 'Fokker 70', tipo: 'Regional', passageiros: '85', autonomia: '2.900 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 1993.', 'Foi uma evolução da linha Fokker 100 com foco em eficiência regional.', 'Sua operação era reforçada por bom rendimento e versatilidade de mercado.'] },
	{ manufacturer: 'Fokker', name: 'Fokker 100', image: 'https://passageirodeprimeira.com/wp-content/uploads/2019/01/Fokker-tam.jpg', alt: 'Fokker 100', tipo: 'Regional', passageiros: '109', autonomia: '2.600 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1988.', 'Era muito utilizada em rotas regionais e de média distância por sua eficiência.', 'Sua cabine confortável e operação econômica a fizeram ser bem aceita.'] },

	{ manufacturer: 'Ilyushin', name: 'Il-62', image: 'https://i.redd.it/never-a-bad-day-to-fly-the-il-62-v0-f4ns0v1rahdc1.png?width=2980&format=png&auto=webp&s=23477e8b75a40454bddd666a4b730d064ee62024', alt: 'Ilyushin Il-62', tipo: 'Longo curso', passageiros: '200', autonomia: '7.200 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1967.', 'Foi um dos grandes jatos de longo curso da União Soviética e manteve grande relevância histórica.', 'Sua capacidade e alcance reforçaram o transporte intercontinental do bloco soviético.'] },
	{ manufacturer: 'Ilyushin', name: 'Il-76', image: 'https://www.aereo.jor.br/wp-content/uploads//2022/02/Il-76.jpg', alt: 'Ilyushin Il-76', tipo: 'Carga', passageiros: '140', autonomia: '5.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1971.', 'É um dos grandes cargueiros do mundo, conhecido por operar em pistas desafiadoras.', 'Sua capacidade de carga e alcance o tornaram essencial para operações pesadas.'], sketchfabId: 'ab71a5f790f940798cc755246a7a8a7f', sketchfabAuthor: 'helijah' },
	{ manufacturer: 'Ilyushin', name: 'Il-86', image: 'https://www.flugzeuginfo.net/acimages/il86_teemutuuri.jpg', alt: 'Ilyushin Il-86', tipo: 'Longo curso', passageiros: '350', autonomia: '5.100 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1980.', 'Foi um dos grandes jatos de fuselagem larga dos anos 80 e 90.', 'Sua estrutura e capacidade reforçaram a operação em rotas de massa.'], sketchfabId: 'e6b517cbb59a4226b302d8a36c0b6aaa', sketchfabAuthor: 'manilov.ap' },
	{ manufacturer: 'Ilyushin', name: 'Il-96', image: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Aeroflot_Il-96-300_RA-96008_SVO_2011-3-10.png?utm_source=pt.wikipedia.org&utm_campaign=index&utm_content=original', alt: 'Ilyushin Il-96', tipo: 'Longo curso', passageiros: '300', autonomia: '9.000 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1992.', 'Tem forte presença em voos de longa distância e cabine ampla para passageiros.', 'A aeronave se destacou em rotas internacionais de grande alcance.'], sketchfabId: '728077500d54422b8c1daf74789855b7', sketchfabAuthor: 'manilov.ap' },

	{ manufacturer: 'Lockheed', name: 'L-1011 TriStar', image: 'https://upload.wikimedia.org/wikipedia/commons/4/49/TAP_Air_Portugal_L-1011-500_CS-TEF_LIS_1988-6-30.png?utm_source=pt.wikipedia.org&utm_campaign=index&utm_content=original', alt: 'Lockheed L-1011 TriStar', tipo: 'Longo curso', passageiros: '400', autonomia: '8.500 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1972.', 'Foi um dos grandes trijatos de longo curso do seu período, com forte alcance internacional.', 'Sua cabine ampla e capacidade em voos de longo curso fizeram seu nome.'], sketchfabId: 'eb8ca32093804259b1522f01c57ca0ab', sketchfabAuthor: 'manilov.ap' },
	{ manufacturer: 'Lockheed', name: 'C-130 Hercules', image: 'https://www.aeroflap.com.br/wp-content/uploads/2019/10/MP19-0865_C-130J-5884-Delivery_004_DM-1.jpg', alt: 'Lockheed C-130 Hercules', tipo: 'Transporte militar', passageiros: '92', autonomia: '3.800 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 1954.', 'É um dos transportes militares mais versáteis do mundo, com grande confiabilidade.', 'Sua capacidade de operação em pistas curtas o torna extremamente útil.'], sketchfabId: 'f5fae27c4270472fac399055699facb4', sketchfabAuthor: 'ioai25312' },
	{ manufacturer: 'Lockheed', name: 'C-5 Galaxy', image: 'https://media.defense.gov/2017/Jun/28/2001770066/-1/-1/0/170628-F-IO108-001.JPG', alt: 'Lockheed C-5 Galaxy', tipo: 'Carga pesada', passageiros: '80', autonomia: '4.500 km', velocidade: 'Mach 0.7', velocidadeKmh: 744, descricao: ['Produção iniciada em 1969.', 'É uma das maiores aeronaves de transporte estratégico do mundo.', 'Sua capacidade de carga pesa no uso em operações de mobilidade militar.'], sketchfabId: '6c3a4d70c6bd40d08bd1d2766148c0c4', sketchfabAuthor: 'jratanatharathorn' },

	{ manufacturer: 'Saab', name: 'Saab 340', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs6remLKdpGdPozi2M2ztBf7mVSdNYWNinY-giQ2Zb5cD2F_kyF0N3mMU&s=10', alt: 'Saab 340', tipo: 'Turboélice', passageiros: '34', autonomia: '1.200 km', velocidade: 'Mach 0.5', velocidadeKmh: 530, descricao: ['Produção iniciada em 1990.', 'Tem boa aceitação em redes regionais por seu conforto e operação eficiente.', 'Sua proposta é bem alinhada com voos curtos e de boa ocupação.'], sketchfabId: '03fa59931efc469789bfd811665acbb5', sketchfabAuthor: 'sofyankurniawan' },
	{ manufacturer: 'Saab', name: 'Saab 2000', image: 'https://www.pjsgroup.com/wp-content/uploads/2019/12/saab-2000-01-1.jpeg', alt: 'Saab 2000', tipo: 'Turboélice', passageiros: '50', autonomia: '2.000 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 1994.', 'Foi desenvolvido para atender rotas regionais com conforto e boa performance.', 'Seu design reforça a eficiência em operações de conexão regional.'] },

	{ manufacturer: 'Tupolev', name: 'Tupolev Tu-134', image: 'https://mf.b37mrtl.ru/rbthmedia/images/2022.02/original/620b8280155bdd377d594814.jpg', alt: 'Tupolev Tu-134', tipo: 'Regional', passageiros: '80', autonomia: '2.500 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1963.', 'Foi um jato regional muito usado em redes domésticas e de média rota.', 'Seu papel histórico é relevante para a evolução dos aviões comerciais soviéticos.'], sketchfabId: '725ba7f81f494f4ebf7117056bfb69fc', sketchfabAuthor: 'helijah' },
	{ manufacturer: 'Tupolev', name: 'Tupolev Tu-154', image: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Tupolev_Tu-154M%2C_Iran_Air_Tours_JP6511800.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original', alt: 'Tupolev Tu-154', tipo: 'Médio/Longo curso', passageiros: '180', autonomia: '4.700 km', velocidade: 'Mach 0.86', velocidadeKmh: 915, descricao: ['Produção iniciada em 1968.', 'Foi um dos aviões de médio e longo alcance mais importantes da antiga União Soviética.', 'Seu uso marcou a era dos jatos de fuselagem estreita de alta capacidade.'], sketchfabId: '32d5c68997ae4f8791a1b25b09ad1fb7', sketchfabAuthor: '1883' },
	{ manufacturer: 'Tupolev', name: 'Tupolev Tu-204', image: 'https://upload.wikimedia.org/wikipedia/commons/9/92/Tupolev_Tu-204-100_%28RA-64047%29_-_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original', alt: 'Tupolev Tu-204', tipo: 'Longo curso', passageiros: '210', autonomia: '5.500 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1989.', 'Foi um dos principais jatos comerciais modernos da Tupolev para mercados de grande demanda.', 'Sua composição eficiente e operação regular o mantiveram relevante no segmento de linha aérea.'] },
	{ manufacturer: 'Tupolev', name: 'Tupolev Tu-214', image: 'https://aeroin.net/wp-content/uploads/2022/06/Russian_Air_Force_Tu-214ON_RA-64519_UUBW_2011-8-12-copiar-1024x683.jpg', alt: 'Tupolev Tu-214', tipo: 'Longo curso', passageiros: '220', autonomia: '6.700 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1996.', 'É uma evolução do Tu-204 com foco em maior alcance e confiabilidade operacional.', 'Sua presença é relevante no contexto de aeronaves comerciais russas e de fuselagem estreita.'] }
];

/*
 * Nacionalidade dos fabricantes, conforme pesquisa pública (sede histórica/atual).
 * countryCode segue ISO 3166-1 alpha-2, usado para os ícones de bandeira na página Modelos.
 */
window.MANUFACTURER_INFO = {
	'Airbus': { country: 'França', countryCode: 'fr', hq: 'Toulouse', logo: '/images/logos/manufacturers/airbus.svg' },
	'Boeing': { country: 'Estados Unidos', countryCode: 'us', hq: 'Arlington, Virginia', logo: '/images/logos/manufacturers/boeing.svg' },
	'Embraer': { country: 'Brasil', countryCode: 'br', hq: 'São José dos Campos, SP', logo: '/images/logos/manufacturers/embraer.svg' },
	'McDonnell Douglas': { country: 'Estados Unidos', countryCode: 'us', hq: 'St. Louis, Missouri', logo: '/images/logos/manufacturers/mcdonnell-douglas.svg' },
	'ATR': { country: 'França', countryCode: 'fr', hq: 'Blagnac (Toulouse) — joint-venture franco-italiana', logo: '/images/logos/manufacturers/atr.svg' },
	'Bombardier': { country: 'Canadá', countryCode: 'ca', hq: 'Montreal, Quebec', logo: '/images/logos/manufacturers/bombardier.svg' },
	'Cessna': { country: 'Estados Unidos', countryCode: 'us', hq: 'Wichita, Kansas', logo: '/images/logos/manufacturers/cessna.svg' },
	'Fokker': { country: 'Países Baixos', countryCode: 'nl', hq: 'Amsterdã', logo: '/images/logos/manufacturers/fokker.png' },
	'Ilyushin': { country: 'Rússia', countryCode: 'ru', hq: 'Moscou', logo: '/images/logos/manufacturers/ilyushin.png' },
	'Lockheed': { country: 'Estados Unidos', countryCode: 'us', hq: 'Burbank, Califórnia', logo: '/images/logos/manufacturers/lockheed.png' },
	'Saab': { country: 'Suécia', countryCode: 'se', hq: 'Linköping', logo: '/images/logos/manufacturers/saab.svg' },
	'Tupolev': { country: 'Rússia', countryCode: 'ru', hq: 'Moscou', logo: '/images/logos/manufacturers/tupolev.svg' }
};
