/*
 * Fonte única dos modelos de aeronaves usados em Modelos e no Simulador de Voo.
 * velocidadeKmh é a velocidade de cruzeiro em km/h usada no cálculo de tempo de voo
 * (derivada de "velocidade" quando esta é um número Mach: km/h = Mach * 1063).
 */
window.AIRCRAFT_MODELS = [
	{ manufacturer: 'Airbus', name: 'Airbus A320neo', image: 'https://www.aircraft.airbus.com/sites/g/files/jlcbta126/files/styles/w1200h675/public/2025-10/Aircraft.Airbus%20Figma%20Images%20V2_A320neo.png?h=eb58b4d6&itok=m1AYlns4', alt: 'Airbus A320neo', tipo: 'Widebody', passageiros: '180', autonomia: '6.100 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2016.', 'É uma das famílias mais utilizadas em rotas médias e de alta demanda.', 'Seu projeto prioriza eficiência, capacidade e operação econômica.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A330neo', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A330neo', tipo: 'Longo curso', passageiros: '300', autonomia: '12.500 km', velocidade: 'Mach 0.86', velocidadeKmh: 915, descricao: ['Produção iniciada em 2018.', 'Sua cabine ampla e maior eficiência ajudam em rotas intercontinentais.', 'É uma opção muito valorizada por companhias de longo curso.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A350', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A350', tipo: 'Longo curso', passageiros: '325', autonomia: '16.100 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 2015.', 'É conhecida por baixo consumo e cabine silenciosa para longas distâncias.', 'Sua tecnologia reforça conforto e alcance em voos de grande extensão.'] },

	{ manufacturer: 'Boeing', name: 'Boeing 737 MAX 8', image: 'https://www.melhoresdestinos.com.br/wp-content/uploads/2026/05/boeing-737-max-8.jpeg', alt: 'Boeing 737 MAX 8', tipo: 'Single-aisle', passageiros: '178', autonomia: '6.570 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 2017.', 'É um modelo muito usado em rotas domésticas e regionais de alta frequência.', 'Sua proposta combina capacidade, eficiência e operação em alta demanda.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 777-300ER', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 777-300ER', tipo: 'Longo curso', passageiros: '396', autonomia: '13.650 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 2004.', 'Destaca-se por grande capacidade e alcance em voos internacionais.', 'É uma das aeronaves mais importantes em rotas de alta densidade.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 787 Dreamliner', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 787 Dreamliner', tipo: 'Longo curso', passageiros: '318', autonomia: '14.140 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 2011.', 'Sua estrutura leve em compósito reduz peso e melhora a eficiência do combustível.', 'É reconhecido pelo conforto da cabine e o desempenho de longo alcance.'] },

	{ manufacturer: 'Embraer', name: 'Embraer E175', image: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer E175', tipo: 'Regional', passageiros: '76', autonomia: '3.300 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2004.', 'É muito usada em redes regionais por sua versatilidade e operação econômica.', 'Seu tamanho e eficiência o tornam ideal para voos de curta e média distância.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E190-E2', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer E190-E2', tipo: 'Regional', passageiros: '114', autonomia: '5.500 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2018.', 'Tem cabine mais silenciosa e boa eficiência operacional em rotas médias.', 'É uma escolha frequente para mercados com alta necessidade regional.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E195-E2', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer E195-E2', tipo: 'Regional', passageiros: '136', autonomia: '5.000 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2019.', 'É destaque em rotas densas e de alta demanda com maior conforto a bordo.', 'Sua capacidade e economia operacional reforçam a eficiência regional.'] },

	{ manufacturer: 'McDonnell Douglas', name: 'MD-80', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'McDonnell Douglas MD-80', tipo: 'Single-aisle', passageiros: '172', autonomia: '4.000 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1980.', 'A família MD-80 foi muito importante na expansão de rotas médias e curtas.', 'Seu desenho clássico marcou uma era da aviação comercial.'] },
	{ manufacturer: 'McDonnell Douglas', name: 'MD-11', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'McDonnell Douglas MD-11', tipo: 'Longo curso', passageiros: '293', autonomia: '10.600 km', velocidade: 'Mach 0.83', velocidadeKmh: 880, descricao: ['Produção iniciada em 1990.', 'Foi um modelo importante para cargas e voos intercontinentais de longa rota.', 'Seu uso se destacou em operações de alcance e capacidade de carga.'] },

	{ manufacturer: 'ATR', name: 'ATR 42-600', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'ATR 42-600', tipo: 'Turboélice', passageiros: '50', autonomia: '1.500 km', velocidade: 'Mach 0.46', velocidadeKmh: 490, descricao: ['Produção iniciada em 2017.', 'É muito eficiente em aeroportos menores e pistas mais curtas.', 'Sua operação é valorizada em redes regionais de baixa densidade.'] },
	{ manufacturer: 'ATR', name: 'ATR 72-600', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'ATR 72-600', tipo: 'Turboélice', passageiros: '70', autonomia: '1.900 km', velocidade: 'Mach 0.48', velocidadeKmh: 510, descricao: ['Produção iniciada em 2010.', 'Faz sucesso em rotas regionais por sua confiabilidade e baixo custo operacional.', 'É uma das opções mais reconhecidas para voos de conexão regional.'] },

	{ manufacturer: 'Aerospatiale', name: 'Aerospatiale Caravelle', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Aerospatiale Caravelle', tipo: 'Jato', passageiros: '140', autonomia: '3.500 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1959.', 'Foi uma aeronave pioneira no conceito de jato comercial de média rota.', 'Sua relevância histórica foi fundamental para o desenvolvimento dos jatos comerciais.'] },
	{ manufacturer: 'Aerospatiale', name: 'SA 330 Puma', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Aerospatiale SA 330 Puma', tipo: 'Helicóptero', passageiros: '18', autonomia: '600 km', velocidade: '220 km/h', velocidadeKmh: 220, descricao: ['Produção iniciada em 1965.', 'É conhecida por robustez operacional e uso em transporte e patrulha militar.', 'Sua capacidade de suporte e confiabilidade impulsionaram sua longa vida útil.'] },

	{ manufacturer: 'Bombardier', name: 'Bombardier CRJ700', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Bombardier CRJ700', tipo: 'Regional', passageiros: '78', autonomia: '3.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2001.', 'Faz parte da geração de jatos regionais com alta eficiência operacional.', 'Sua utilização é muito comum em rotas com boa demanda de passageiros.'] },
	{ manufacturer: 'Bombardier', name: 'Bombardier Q400', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Bombardier Q400', tipo: 'Turboélice', passageiros: '86', autonomia: '2.200 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 2008.', 'É muito respeitada por operar em aeroportos curtos e de baixa demanda.', 'Se destaca por conforto, eficiência e boa performance regional.'] },

	{ manufacturer: 'Cessna', name: 'Cessna 172 Skyhawk', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'Cessna 172 Skyhawk', tipo: 'Monomotor', passageiros: '4', autonomia: '1.300 km', velocidade: '220 km/h', velocidadeKmh: 220, descricao: ['Produção iniciada em 1956.', 'É a aeronave mais produzida da história e símbolo do treinamento de pilotos.', 'Sua simplicidade e confiabilidade a tornaram universalmente conhecida.'] },
	{ manufacturer: 'Cessna', name: 'Cessna 208 Caravan', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Cessna 208 Caravan', tipo: 'Turboélice', passageiros: '9', autonomia: '1.500 km', velocidade: '300 km/h', velocidadeKmh: 300, descricao: ['Produção iniciada em 1984.', 'É muito usada em operações regionais, carga leve e acesso a aeroportos menores.', 'Sua versatilidade faz dela um dos modelos mais úteis do segmento.'] },

	{ manufacturer: 'Fokker', name: 'Fokker 50', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Fokker 50', tipo: 'Turboélice', passageiros: '50', autonomia: '2.200 km', velocidade: 'Mach 0.55', velocidadeKmh: 585, descricao: ['Produção iniciada em 1990.', 'Foi uma referência em operação regional confiável em pistas curtas.', 'Sua confiabilidade ajudou a consolidar a operação em rotas de baixa densidade.'] },
	{ manufacturer: 'Fokker', name: 'Fokker 100', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Fokker 100', tipo: 'Regional', passageiros: '109', autonomia: '2.600 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1988.', 'Era muito utilizada em rotas regionais e de média distância por sua eficiência.', 'Sua cabine confortável e operação econômica a fizeram ser bem aceita.'] },

	{ manufacturer: 'Ilyushin', name: 'Il-76', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Ilyushin Il-76', tipo: 'Carga', passageiros: '140', autonomia: '5.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1971.', 'É um dos grandes cargueiros do mundo, conhecido por operar em pistas desafiadoras.', 'Sua capacidade de carga e alcance o tornaram essencial para operações pesadas.'] },
	{ manufacturer: 'Ilyushin', name: 'Il-96', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Ilyushin Il-96', tipo: 'Longo curso', passageiros: '300', autonomia: '9.000 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1992.', 'Tem forte presença em voos de longa distância e cabine ampla para passageiros.', 'A aeronave se destacou em rotas internacionais de grande alcance.'] },

	{ manufacturer: 'Lockheed', name: 'C-130 Hercules', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'Lockheed C-130 Hercules', tipo: 'Transporte militar', passageiros: '92', autonomia: '3.800 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 1954.', 'É um dos transportes militares mais versáteis do mundo, com grande confiabilidade.', 'Sua capacidade de operação em pistas curtas o torna extremamente útil.'] },
	{ manufacturer: 'Lockheed', name: 'L-1011 TriStar', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Lockheed L-1011 TriStar', tipo: 'Longo curso', passageiros: '400', autonomia: '8.500 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1972.', 'Foi um dos grandes trijatos de longo curso do seu período, com forte alcance internacional.', 'Sua cabine ampla e capacidade em voos de longo curso fizeram seu nome.'] },

	{ manufacturer: 'SAAB', name: 'Saab 340', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Saab 340', tipo: 'Turboélice', passageiros: '34', autonomia: '1.200 km', velocidade: 'Mach 0.5', velocidadeKmh: 530, descricao: ['Produção iniciada em 1990.', 'Tem boa aceitação em redes regionais por seu conforto e operação eficiente.', 'Sua proposta é bem alinhada com voos curtos e de boa ocupação.'] },
	{ manufacturer: 'SAAB', name: 'Saab 2000', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Saab 2000', tipo: 'Turboélice', passageiros: '50', autonomia: '2.000 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 1994.', 'Foi desenvolvido para atender rotas regionais com conforto e boa performance.', 'Seu design reforça a eficiência em operações de conexão regional.'] }
];
