/*
 * Fonte única dos modelos de aeronaves usados em Modelos e no Simulador de Voo.
 * velocidadeKmh é a velocidade de cruzeiro em km/h usada no cálculo de tempo de voo
 * (derivada de "velocidade" quando esta é um número Mach: km/h = Mach * 1063).
 */
window.AIRCRAFT_MODELS = [
	{ manufacturer: 'Airbus', name: 'Airbus A220-300', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A220-300', tipo: 'Regional', passageiros: '160', autonomia: '6.300 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2016.', 'É um dos jatos regionais de maior eficiência e apelo operacional.', 'Sua cabine moderna e alcance fazem dele um campeão de rotas de média distância.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A319neo', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A319neo', tipo: 'Single-aisle', passageiros: '156', autonomia: '6.900 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2018.', 'É uma versão enxuta da família A320 com foco em eficiência e densidade.', 'Sua versatilidade é muito útil em rotas domésticas e de curta distância.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A320neo', image: 'https://www.aircraft.airbus.com/sites/g/files/jlcbta126/files/styles/w1200h675/public/2025-10/Aircraft.Airbus%20Figma%20Images%20V2_A320neo.png?h=eb58b4d6&itok=m1AYlns4', alt: 'Airbus A320neo', tipo: 'Single-aisle', passageiros: '180', autonomia: '6.100 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2016.', 'É uma das famílias mais utilizadas em rotas médias e de alta demanda.', 'Seu projeto prioriza eficiência, capacidade e operação econômica.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A321neo', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A321neo', tipo: 'Single-aisle', passageiros: '220', autonomia: '7.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2016.', 'Oferece maior alcance e capacidade em comparação ao A320neo.', 'Seu uso é comum em rotas de alta demanda e média distância.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A330-200', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A330-200', tipo: 'Longo curso', passageiros: '250', autonomia: '13.450 km', velocidade: 'Mach 0.86', velocidadeKmh: 915, descricao: ['Produção iniciada em 1998.', 'Foi uma solução muito eficiente para rotas intercontinentais e fora de hubs.', 'Sua capacidade e alcance impulsionaram o mercado de longo curso.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A330neo', image: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A330neo', tipo: 'Longo curso', passageiros: '300', autonomia: '12.500 km', velocidade: 'Mach 0.86', velocidadeKmh: 915, descricao: ['Produção iniciada em 2018.', 'Sua cabine ampla e maior eficiência ajudam em rotas intercontinentais.', 'É uma opção muito valorizada por companhias de longo curso.'] },
	{ manufacturer: 'Airbus', name: 'Airbus A350-900', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Airbus A350-900', tipo: 'Longo curso', passageiros: '325', autonomia: '16.100 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 2015.', 'É reconhecida por baixo consumo, cabine silenciosa e alcance transcontinental.', 'Sua tecnologia reforça conforto e eficiência em rotas de longa duração.'] },

	{ manufacturer: 'Boeing', name: 'Boeing 737-800', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 737-800', tipo: 'Single-aisle', passageiros: '162', autonomia: '5.700 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 1998.', 'É um dos modelos mais importantes do segmento de jatos de curto e médio alcance.', 'Sua operação é altamente eficiente em redes domésticas e regionais.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 737 MAX 8', image: 'https://www.melhoresdestinos.com.br/wp-content/uploads/2026/05/boeing-737-max-8.jpeg', alt: 'Boeing 737 MAX 8', tipo: 'Single-aisle', passageiros: '178', autonomia: '6.570 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 2017.', 'É um modelo muito usado em rotas domésticas e regionais de alta frequência.', 'Sua proposta combina capacidade, eficiência e operação em alta demanda.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 737 MAX 10', image: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 737 MAX 10', tipo: 'Single-aisle', passageiros: '188', autonomia: '6.790 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 2020.', 'Amplia a capacidade da família MAX para redes de grande demanda.', 'A proposta prioriza eficiência e melhora operacional em aeroportos congestionados.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 747-400', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 747-400', tipo: 'Longo curso', passageiros: '410', autonomia: '13.450 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 1988.', 'Foi um marco da aviação comercial por sua capacidade e alcance.', 'Sua fuselagem ampla o manteve relevante em rotas de grande demanda.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 767-300ER', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 767-300ER', tipo: 'Longo curso', passageiros: '261', autonomia: '11.450 km', velocidade: 'Mach 0.80', velocidadeKmh: 850, descricao: ['Produção iniciada em 1986.', 'Foi uma solução eficiente para rotas intercontinentais e de alta regularidade.', 'Sua utilização se destacou em operação de longo alcance e alto padrão.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 777-300ER', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 777-300ER', tipo: 'Longo curso', passageiros: '396', autonomia: '13.650 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 2004.', 'Destaca-se por grande capacidade e alcance em voos internacionais.', 'É uma das aeronaves mais importantes em rotas de alta densidade.'] },
	{ manufacturer: 'Boeing', name: 'Boeing 787-9 Dreamliner', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Boeing 787-9 Dreamliner', tipo: 'Longo curso', passageiros: '318', autonomia: '14.140 km', velocidade: 'Mach 0.85', velocidadeKmh: 905, descricao: ['Produção iniciada em 2011.', 'Sua estrutura leve em compósito reduz peso e melhora a eficiência do combustível.', 'É reconhecido pelo conforto da cabine e o desempenho de longo alcance.'] },

	{ manufacturer: 'Embraer', name: 'Embraer ERJ 145', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer ERJ 145', tipo: 'Regional', passageiros: '50', autonomia: '3.000 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1996.', 'Foi um avião regional muito usado em conexões domésticas e curtas distâncias.', 'Seu desenho compacto e robustez o tornaram um clássico regional.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E170', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer E170', tipo: 'Regional', passageiros: '80', autonomia: '3.900 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2007.', 'É um dos modelos mais versáteis do segmento regional de baixa e média rotas.', 'Seu desempenho combina conforto e eficiência em operação frequente.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E175', image: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer E175', tipo: 'Regional', passageiros: '76', autonomia: '3.300 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2004.', 'É muito usada em redes regionais por sua versatilidade e operação econômica.', 'Seu tamanho e eficiência o tornam ideal para voos de curta e média distância.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E190-E2', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer E190-E2', tipo: 'Regional', passageiros: '114', autonomia: '5.500 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2018.', 'Tem cabine mais silenciosa e boa eficiência operacional em rotas médias.', 'É uma escolha frequente para mercados com alta necessidade regional.'] },
	{ manufacturer: 'Embraer', name: 'Embraer E195-E2', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Embraer E195-E2', tipo: 'Regional', passageiros: '136', autonomia: '5.000 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2019.', 'É destaque em rotas densas e de alta demanda com maior conforto a bordo.', 'Sua capacidade e economia operacional reforçam a eficiência regional.'] },

	{ manufacturer: 'McDonnell Douglas', name: 'DC-9', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Douglas DC-9', tipo: 'Single-aisle', passageiros: '130', autonomia: '3.500 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1965.', 'Foi um marco da aviação regional de alta frequência e operação econômica.', 'Sua presença no mercado foi fundamental para o crescimento das rotas domésticas.'] },
	{ manufacturer: 'McDonnell Douglas', name: 'MD-80', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'McDonnell Douglas MD-80', tipo: 'Single-aisle', passageiros: '172', autonomia: '4.000 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1980.', 'A família MD-80 foi muito importante na expansão de rotas médias e curtas.', 'Seu desenho clássico marcou uma era da aviação comercial.'] },
	{ manufacturer: 'McDonnell Douglas', name: 'MD-90', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'McDonnell Douglas MD-90', tipo: 'Single-aisle', passageiros: '172', autonomia: '4.100 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1995.', 'Foi uma evolução da linha MD-80 com foco em eficiência e conforto.', 'Sua busca por melhor performance ajudou a manter a família relevante.'] },
	{ manufacturer: 'McDonnell Douglas', name: 'MD-11', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'McDonnell Douglas MD-11', tipo: 'Longo curso', passageiros: '293', autonomia: '10.600 km', velocidade: 'Mach 0.83', velocidadeKmh: 880, descricao: ['Produção iniciada em 1990.', 'Foi um modelo importante para cargas e voos intercontinentais de longa rota.', 'Seu uso se destacou em operações de alcance e capacidade de carga.'] },

	{ manufacturer: 'ATR', name: 'ATR 42-600', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'ATR 42-600', tipo: 'Turboélice', passageiros: '50', autonomia: '1.500 km', velocidade: 'Mach 0.46', velocidadeKmh: 490, descricao: ['Produção iniciada em 2017.', 'É muito eficiente em aeroportos menores e pistas mais curtas.', 'Sua operação é valorizada em redes regionais de baixa densidade.'] },
	{ manufacturer: 'ATR', name: 'ATR 72-500', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'ATR 72-500', tipo: 'Turboélice', passageiros: '68', autonomia: '1.850 km', velocidade: 'Mach 0.48', velocidadeKmh: 510, descricao: ['Produção iniciada em 2007.', 'É uma variante eficiente para rotas regionais e curtas distâncias.', 'Sua operação é reconhecida por confiabilidade e boa performance em aeroportos menores.'] },
	{ manufacturer: 'ATR', name: 'ATR 72-600', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'ATR 72-600', tipo: 'Turboélice', passageiros: '70', autonomia: '1.900 km', velocidade: 'Mach 0.48', velocidadeKmh: 510, descricao: ['Produção iniciada em 2010.', 'Faz sucesso em rotas regionais por sua confiabilidade e baixo custo operacional.', 'É uma das opções mais reconhecidas para voos de conexão regional.'] },

	{ manufacturer: 'Bombardier', name: 'Bombardier CRJ700', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Bombardier CRJ700', tipo: 'Regional', passageiros: '78', autonomia: '3.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2001.', 'Faz parte da geração de jatos regionais com alta eficiência operacional.', 'Sua utilização é muito comum em rotas com boa demanda de passageiros.'] },
	{ manufacturer: 'Bombardier', name: 'Bombardier CRJ900', image: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?auto=format&fit=crop&w=1200&q=80', alt: 'Bombardier CRJ900', tipo: 'Regional', passageiros: '90', autonomia: '3.700 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2007.', 'É uma evolução do CRJ700 para rotas com maior densidade de passageiros.', 'Sua eficiência e boa execução operacional reforçaram seu uso regional.'] },
	{ manufacturer: 'Bombardier', name: 'Bombardier Q400', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Bombardier Q400', tipo: 'Turboélice', passageiros: '86', autonomia: '2.200 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 2008.', 'É muito respeitada por operar em aeroportos curtos e de baixa demanda.', 'Se destaca por conforto, eficiência e boa performance regional.'] },
	{ manufacturer: 'Bombardier', name: 'Bombardier Q300', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Bombardier Q300', tipo: 'Turboélice', passageiros: '56', autonomia: '1.750 km', velocidade: 'Mach 0.56', velocidadeKmh: 595, descricao: ['Produção iniciada em 1998.', 'É uma opção confiável para rotas de baixa densidade e pistas curtas.', 'Sua operação combina eficiência regional e conforto de cabine.'] },

	{ manufacturer: 'Cessna', name: 'Cessna 172 Skyhawk', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'Cessna 172 Skyhawk', tipo: 'Monomotor', passageiros: '4', autonomia: '1.300 km', velocidade: '220 km/h', velocidadeKmh: 220, descricao: ['Produção iniciada em 1956.', 'É a aeronave mais produzida da história e símbolo do treinamento de pilotos.', 'Sua simplicidade e confiabilidade a tornaram universalmente conhecida.'] },
	{ manufacturer: 'Cessna', name: 'Cessna 208 Caravan', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Cessna 208 Caravan', tipo: 'Turboélice', passageiros: '9', autonomia: '1.500 km', velocidade: '300 km/h', velocidadeKmh: 300, descricao: ['Produção iniciada em 1984.', 'É muito usada em operações regionais, carga leve e acesso a aeroportos menores.', 'Sua versatilidade faz dela um dos modelos mais úteis do segmento.'] },
	{ manufacturer: 'Cessna', name: 'Cessna Citation Bravo', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Cessna Citation Bravo', tipo: 'Jato executivo', passageiros: '8', autonomia: '3.000 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 2005.', 'É uma plataforma executiva reconhecida pela combinação de alcance e conforto.', 'Seu uso é muito valorizado em viagens rápidas de negócios e lazer.'] },
	{ manufacturer: 'Cessna', name: 'Cessna Citation CJ4', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Cessna Citation CJ4', tipo: 'Jato executivo', passageiros: '10', autonomia: '3.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 2010.', 'Combina alcance, conforto e operação eficiente para voos executivos.', 'É muito valorizada em deslocamentos rápidos com boa produtividade.'] },

	{ manufacturer: 'Fokker', name: 'Fokker 50', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Fokker 50', tipo: 'Turboélice', passageiros: '50', autonomia: '2.200 km', velocidade: 'Mach 0.55', velocidadeKmh: 585, descricao: ['Produção iniciada em 1990.', 'Foi uma referência em operação regional confiável em pistas curtas.', 'Sua confiabilidade ajudou a consolidar a operação em rotas de baixa densidade.'] },
	{ manufacturer: 'Fokker', name: 'Fokker 70', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Fokker 70', tipo: 'Regional', passageiros: '85', autonomia: '2.900 km', velocidade: 'Mach 0.79', velocidadeKmh: 840, descricao: ['Produção iniciada em 1993.', 'Foi uma evolução da linha Fokker 100 com foco em eficiência regional.', 'Sua operação era reforçada por bom rendimento e versatilidade de mercado.'] },
	{ manufacturer: 'Fokker', name: 'Fokker 100', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Fokker 100', tipo: 'Regional', passageiros: '109', autonomia: '2.600 km', velocidade: 'Mach 0.8', velocidadeKmh: 850, descricao: ['Produção iniciada em 1988.', 'Era muito utilizada em rotas regionais e de média distância por sua eficiência.', 'Sua cabine confortável e operação econômica a fizeram ser bem aceita.'] },

	{ manufacturer: 'Ilyushin', name: 'Il-62', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Ilyushin Il-62', tipo: 'Longo curso', passageiros: '200', autonomia: '7.200 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1967.', 'Foi um dos grandes jatos de longo curso da União Soviética e manteve grande relevância histórica.', 'Sua capacidade e alcance reforçaram o transporte intercontinental do bloco soviético.'] },
	{ manufacturer: 'Ilyushin', name: 'Il-76', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Ilyushin Il-76', tipo: 'Carga', passageiros: '140', autonomia: '5.400 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1971.', 'É um dos grandes cargueiros do mundo, conhecido por operar em pistas desafiadoras.', 'Sua capacidade de carga e alcance o tornaram essencial para operações pesadas.'] },
	{ manufacturer: 'Ilyushin', name: 'Il-86', image: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?auto=format&fit=crop&w=1200&q=80', alt: 'Ilyushin Il-86', tipo: 'Longo curso', passageiros: '350', autonomia: '5.100 km', velocidade: 'Mach 0.82', velocidadeKmh: 870, descricao: ['Produção iniciada em 1980.', 'Foi um dos grandes jatos de fuselagem larga dos anos 80 e 90.', 'Sua estrutura e capacidade reforçaram a operação em rotas de massa.'] },
	{ manufacturer: 'Ilyushin', name: 'Il-96', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Ilyushin Il-96', tipo: 'Longo curso', passageiros: '300', autonomia: '9.000 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1992.', 'Tem forte presença em voos de longa distância e cabine ampla para passageiros.', 'A aeronave se destacou em rotas internacionais de grande alcance.'] },

	{ manufacturer: 'Lockheed', name: 'L-1011 TriStar', image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80', alt: 'Lockheed L-1011 TriStar', tipo: 'Longo curso', passageiros: '400', autonomia: '8.500 km', velocidade: 'Mach 0.84', velocidadeKmh: 895, descricao: ['Produção iniciada em 1972.', 'Foi um dos grandes trijatos de longo curso do seu período, com forte alcance internacional.', 'Sua cabine ampla e capacidade em voos de longo curso fizeram seu nome.'] },
	{ manufacturer: 'Lockheed', name: 'C-130 Hercules', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80', alt: 'Lockheed C-130 Hercules', tipo: 'Transporte militar', passageiros: '92', autonomia: '3.800 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 1954.', 'É um dos transportes militares mais versáteis do mundo, com grande confiabilidade.', 'Sua capacidade de operação em pistas curtas o torna extremamente útil.'] },
	{ manufacturer: 'Lockheed', name: 'C-5 Galaxy', image: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80', alt: 'Lockheed C-5 Galaxy', tipo: 'Carga pesada', passageiros: '80', autonomia: '4.500 km', velocidade: 'Mach 0.7', velocidadeKmh: 744, descricao: ['Produção iniciada em 1969.', 'É uma das maiores aeronaves de transporte estratégico do mundo.', 'Sua capacidade de carga pesa no uso em operações de mobilidade militar.'] },

	{ manufacturer: 'Saab', name: 'Saab 340', image: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80', alt: 'Saab 340', tipo: 'Turboélice', passageiros: '34', autonomia: '1.200 km', velocidade: 'Mach 0.5', velocidadeKmh: 530, descricao: ['Produção iniciada em 1990.', 'Tem boa aceitação em redes regionais por seu conforto e operação eficiente.', 'Sua proposta é bem alinhada com voos curtos e de boa ocupação.'] },
	{ manufacturer: 'Saab', name: 'Saab 2000', image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80', alt: 'Saab 2000', tipo: 'Turboélice', passageiros: '50', autonomia: '2.000 km', velocidade: 'Mach 0.6', velocidadeKmh: 640, descricao: ['Produção iniciada em 1994.', 'Foi desenvolvido para atender rotas regionais com conforto e boa performance.', 'Seu design reforça a eficiência em operações de conexão regional.'] }
];
